/*
SQLyog Enterprise - MySQL GUI v8.1 
MySQL - 5.6.21 : Database - travelaja
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE /*!32312 IF NOT EXISTS*/`travelaja` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `travelaja`;

/*Table structure for table `agen_type` */

DROP TABLE IF EXISTS `agen_type`;

CREATE TABLE `agen_type` (
  `AGENT_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGENT_TYPE_NAME` varchar(100) DEFAULT NULL,
  `AGENT_TYPE_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `AGENT_TYPE_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `AGENT_TYPE_UPDATEBY` int(11) DEFAULT NULL,
  `AGENT_TYPE_CREATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`AGENT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `agen_type` */

/*Table structure for table `agent` */

DROP TABLE IF EXISTS `agent`;

CREATE TABLE `agent` (
  `AGENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGENT_TYPE_ID` int(11) DEFAULT NULL,
  `AGENT_NAME` varchar(100) DEFAULT NULL,
  `AGENT_USERNAME` varchar(100) DEFAULT NULL,
  `AGENT_PASSWORD` varchar(100) DEFAULT NULL,
  `AGENT_EMAIL` varchar(100) DEFAULT NULL,
  `AGENT_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`AGENT_ID`),
  KEY `FK_RELATIONSHIP_15` (`AGENT_TYPE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_15` FOREIGN KEY (`AGENT_TYPE_ID`) REFERENCES `agen_type` (`AGENT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `agent` */

/*Table structure for table `agent_typexroles` */

DROP TABLE IF EXISTS `agent_typexroles`;

CREATE TABLE `agent_typexroles` (
  `AGENT_TYPE_ID` int(11) NOT NULL,
  `ROLES_ID` int(11) NOT NULL,
  PRIMARY KEY (`AGENT_TYPE_ID`,`ROLES_ID`),
  KEY `FK_RELATIONSHIP_24` (`ROLES_ID`),
  CONSTRAINT `FK_RELATIONSHIP_18` FOREIGN KEY (`AGENT_TYPE_ID`) REFERENCES `agen_type` (`AGENT_TYPE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_24` FOREIGN KEY (`ROLES_ID`) REFERENCES `roles` (`ROLES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `agent_typexroles` */

/*Table structure for table `city` */

DROP TABLE IF EXISTS `city`;

CREATE TABLE `city` (
  `CITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CITY_NAME` varchar(100) DEFAULT NULL,
  `CITY_UPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CITY_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CITY_UPDATEBY` int(11) DEFAULT NULL,
  `CITY_CREATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`CITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Data for the table `city` */

insert  into `city`(CITY_ID,CITY_NAME,CITY_UPDATE,CITY_CREATE,CITY_UPDATEBY,CITY_CREATEBY) values (1,'surabaya','2015-08-18 20:20:54','0000-00-00 00:00:00',NULL,NULL),(2,'malang','2015-08-18 20:21:46','2015-08-18 20:21:46',NULL,NULL);

/*Table structure for table `hak_akses` */

DROP TABLE IF EXISTS `hak_akses`;

CREATE TABLE `hak_akses` (
  `ROLES_ID` int(11) NOT NULL,
  `MODULES_ID` int(11) NOT NULL,
  `SUB_MODULES_ID` int(11) DEFAULT NULL,
  `HAK_AKSES` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `hak_akses` */

/*Table structure for table `log_transaction` */

DROP TABLE IF EXISTS `log_transaction`;

CREATE TABLE `log_transaction` (
  `LOG_TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRANSACTION_TYPE_ID` int(11) DEFAULT NULL,
  `TRA_TRANSACTION_TYPE_ID` int(11) DEFAULT NULL,
  `TRA_TRANSACTION_TYPE_ID2` int(11) DEFAULT NULL,
  `TRAVEL_TRANSACTION_ID` int(11) DEFAULT NULL,
  `TICKET_TRANSACTION_ID` int(11) DEFAULT NULL,
  `LOG_TRANSACTION_ACTIVITY` varchar(100) DEFAULT NULL,
  `LOG_TRANSACTION_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LOG_TRANSACTION_CREATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`LOG_TRANSACTION_ID`),
  KEY `FK_RELATIONSHIP_2` (`TICKET_TRANSACTION_ID`),
  KEY `FK_RELATIONSHIP_31` (`TRAVEL_TRANSACTION_ID`),
  KEY `FK_RELATIONSHIP_38` (`TRA_TRANSACTION_TYPE_ID`),
  KEY `FK_RELATIONSHIP_39` (`TRA_TRANSACTION_TYPE_ID2`),
  KEY `FK_RELATIONSHIP_40` (`TRANSACTION_TYPE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_2` FOREIGN KEY (`TICKET_TRANSACTION_ID`) REFERENCES `ticket_transaction` (`TICKET_TRANSACTION_ID`),
  CONSTRAINT `FK_RELATIONSHIP_31` FOREIGN KEY (`TRAVEL_TRANSACTION_ID`) REFERENCES `travel_transaction` (`TRAVEL_TRANSACTION_ID`),
  CONSTRAINT `FK_RELATIONSHIP_38` FOREIGN KEY (`TRA_TRANSACTION_TYPE_ID`) REFERENCES `transaction_type` (`TRANSACTION_TYPE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_39` FOREIGN KEY (`TRA_TRANSACTION_TYPE_ID2`) REFERENCES `transaction_type` (`TRANSACTION_TYPE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_40` FOREIGN KEY (`TRANSACTION_TYPE_ID`) REFERENCES `transaction_type` (`TRANSACTION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `log_transaction` */

/*Table structure for table `member` */

DROP TABLE IF EXISTS `member`;

CREATE TABLE `member` (
  `MEMBER_EMAIL` varchar(100) DEFAULT NULL,
  `MEMBER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEMBER_NAME` varchar(100) DEFAULT NULL,
  `MEMBER_PASSWORD` varchar(100) DEFAULT NULL,
  `MEMBER_USERNAME` varchar(100) DEFAULT NULL,
  `MEMBER_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MEMBER_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MEMBER_CREATEBY` int(11) DEFAULT NULL,
  `MEMBER_UPDATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `member` */

/*Table structure for table `modules` */

DROP TABLE IF EXISTS `modules`;

CREATE TABLE `modules` (
  `MODULES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODULES_NAME` varchar(100) DEFAULT NULL,
  `MODULES_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODULES_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MODULES_CREATEBY` int(11) DEFAULT NULL,
  `MODULES_UPDATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`MODULES_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Data for the table `modules` */

insert  into `modules`(MODULES_ID,MODULES_NAME,MODULES_CREATE,MODULES_UPDATE,MODULES_CREATEBY,MODULES_UPDATEBY) values (1,'user management','2015-08-13 14:21:54','0000-00-00 00:00:00',NULL,NULL),(2,'tes','2015-08-18 10:39:59','0000-00-00 00:00:00',NULL,NULL);

/*Table structure for table `partner` */

DROP TABLE IF EXISTS `partner`;

CREATE TABLE `partner` (
  `PARTNER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARTNER_NAME` varchar(100) DEFAULT NULL,
  `PARTNER_ADDRESS` varchar(400) DEFAULT NULL,
  `PARTNER_TELP` varchar(20) DEFAULT NULL,
  `PARTNER_DESCRIPTION` varchar(2000) DEFAULT NULL,
  `PARTNER_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PARTNER_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `PARTNER_CREATEBY` int(11) DEFAULT NULL,
  `PARTNER_UPDATEBY` int(11) DEFAULT NULL,
  `PARTNER_PHOTO` varchar(50) DEFAULT NULL,
  `PARTNER_USERNAME` varchar(100) DEFAULT NULL,
  `PARTNER_PASSWORD` varchar(100) DEFAULT NULL,
  `PARTNER_EMAIL` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`PARTNER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `partner` */

insert  into `partner`(PARTNER_ID,PARTNER_NAME,PARTNER_ADDRESS,PARTNER_TELP,PARTNER_DESCRIPTION,PARTNER_CREATE,PARTNER_UPDATE,PARTNER_CREATEBY,PARTNER_UPDATEBY,PARTNER_PHOTO,PARTNER_USERNAME,PARTNER_PASSWORD,PARTNER_EMAIL) values (1,'ripas','surabaya','0808','lalla','2015-08-18 20:22:34','0000-00-00 00:00:00',NULL,NULL,NULL,NULL,'123',NULL);

/*Table structure for table `passenger_detail` */

DROP TABLE IF EXISTS `passenger_detail`;

CREATE TABLE `passenger_detail` (
  `TICKET_TRANSACTION_ID` int(11) DEFAULT NULL,
  `PASSENGER_DETAIL_NAME` varchar(100) DEFAULT NULL,
  `PASSENGER_DETAIL_KTP` varchar(100) DEFAULT NULL,
  `PASSENGER_DETAIL_TITTLE` varchar(10) DEFAULT NULL,
  `PASSENGER_DETAIL_TELP` varchar(50) DEFAULT NULL,
  KEY `FK_RELATIONSHIP_41` (`TICKET_TRANSACTION_ID`),
  CONSTRAINT `FK_RELATIONSHIP_41` FOREIGN KEY (`TICKET_TRANSACTION_ID`) REFERENCES `ticket_transaction` (`TICKET_TRANSACTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `passenger_detail` */

/*Table structure for table `penggunaxroles` */

DROP TABLE IF EXISTS `penggunaxroles`;

CREATE TABLE `penggunaxroles` (
  `USERS_ID` int(11) NOT NULL,
  `ROLES_ID` int(11) NOT NULL,
  PRIMARY KEY (`USERS_ID`,`ROLES_ID`),
  KEY `FK_RELATIONSHIP_6` (`ROLES_ID`),
  CONSTRAINT `FK_RELATIONSHIP_5` FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`),
  CONSTRAINT `FK_RELATIONSHIP_6` FOREIGN KEY (`ROLES_ID`) REFERENCES `roles` (`ROLES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `penggunaxroles` */

insert  into `penggunaxroles`(USERS_ID,ROLES_ID) values (1,1);

/*Table structure for table `point` */

DROP TABLE IF EXISTS `point`;

CREATE TABLE `point` (
  `POINT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `POINT_STATUS_ID` int(11) DEFAULT NULL,
  `POINT_NAME` varchar(100) DEFAULT NULL,
  `POINT_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `POINT_CREATEBY` int(11) DEFAULT NULL,
  `POINT_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `POINT_UPDATEBY` int(11) DEFAULT NULL,
  `POINT_STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`POINT_ID`),
  KEY `FK_RELATIONSHIP_13` (`POINT_STATUS_ID`),
  CONSTRAINT `FK_RELATIONSHIP_13` FOREIGN KEY (`POINT_STATUS_ID`) REFERENCES `point_status` (`POINT_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `point` */

/*Table structure for table `point_status` */

DROP TABLE IF EXISTS `point_status`;

CREATE TABLE `point_status` (
  `POINT_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `POINT_STATUS_NAME` varchar(100) DEFAULT NULL,
  `POINT_STATUS_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `POINT_STATUS_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `POINT_STATUS_CREATEBY` int(11) DEFAULT NULL,
  `POINT_STATUS_UPDATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`POINT_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `point_status` */

/*Table structure for table `pointxmember` */

DROP TABLE IF EXISTS `pointxmember`;

CREATE TABLE `pointxmember` (
  `POINT_ID` int(11) NOT NULL,
  `MEMBER_ID` int(11) NOT NULL,
  PRIMARY KEY (`POINT_ID`,`MEMBER_ID`),
  KEY `FK_RELATIONSHIP_42` (`MEMBER_ID`),
  CONSTRAINT `FK_RELATIONSHIP_14` FOREIGN KEY (`POINT_ID`) REFERENCES `point` (`POINT_ID`),
  CONSTRAINT `FK_RELATIONSHIP_42` FOREIGN KEY (`MEMBER_ID`) REFERENCES `member` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `pointxmember` */

/*Table structure for table `rent_schedule` */

DROP TABLE IF EXISTS `rent_schedule`;

CREATE TABLE `rent_schedule` (
  `RENT_SCHEDULE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RENT_SCHEDULE_DATE` date DEFAULT NULL,
  `RENT_SCHEDULE_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RENT_SCHEDULE_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `RENT_SCHEDULE_UPDATEBY` int(11) DEFAULT NULL,
  `RENT_SCHEDULE_CREATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`RENT_SCHEDULE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `rent_schedule` */

/*Table structure for table `rent_transaction` */

DROP TABLE IF EXISTS `rent_transaction`;

CREATE TABLE `rent_transaction` (
  `RENT_TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOG_TRANSACTION_ID` int(11) DEFAULT NULL,
  `STATUS_TRANSACTION_RENT_ID` int(11) DEFAULT NULL,
  `MEMBER_ID` int(11) DEFAULT NULL,
  `RENT_TRANSACTION_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `RENT_TRANSACTION_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `RENT_TRANSACTION_PRICE` int(11) DEFAULT NULL,
  `RENT_TRANSACTION_DURATION` int(11) DEFAULT NULL,
  `RENT_TRANSACTION_CREATEBY` int(11) DEFAULT NULL,
  `RENT_TRANSACTION_UPDATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`RENT_TRANSACTION_ID`),
  KEY `FK_RELATIONSHIP_17` (`STATUS_TRANSACTION_RENT_ID`),
  KEY `FK_RELATIONSHIP_25` (`LOG_TRANSACTION_ID`),
  KEY `FK_RELATIONSHIP_29` (`MEMBER_ID`),
  CONSTRAINT `FK_RELATIONSHIP_17` FOREIGN KEY (`STATUS_TRANSACTION_RENT_ID`) REFERENCES `status_transaction_rent` (`STATUS_TRANSACTION_RENT_ID`),
  CONSTRAINT `FK_RELATIONSHIP_25` FOREIGN KEY (`LOG_TRANSACTION_ID`) REFERENCES `log_transaction` (`LOG_TRANSACTION_ID`),
  CONSTRAINT `FK_RELATIONSHIP_29` FOREIGN KEY (`MEMBER_ID`) REFERENCES `member` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `rent_transaction` */

/*Table structure for table `rent_transaction_detail` */

DROP TABLE IF EXISTS `rent_transaction_detail`;

CREATE TABLE `rent_transaction_detail` (
  `RENT_TRANSACTION_ID` int(11) NOT NULL,
  `RENT_SCHEDULE_ID` int(11) NOT NULL,
  PRIMARY KEY (`RENT_TRANSACTION_ID`,`RENT_SCHEDULE_ID`),
  KEY `FK_RELATIONSHIP_30` (`RENT_SCHEDULE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_27` FOREIGN KEY (`RENT_TRANSACTION_ID`) REFERENCES `rent_transaction` (`RENT_TRANSACTION_ID`),
  CONSTRAINT `FK_RELATIONSHIP_30` FOREIGN KEY (`RENT_SCHEDULE_ID`) REFERENCES `rent_schedule` (`RENT_SCHEDULE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `rent_transaction_detail` */

/*Table structure for table `roles` */

DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `ROLES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLES_NAME` varchar(100) DEFAULT NULL,
  `ROLES_UPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ROLES_CREATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ROLES_UPDATEBY` int(11) DEFAULT NULL,
  `ROLES_CREATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ROLES_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `roles` */

insert  into `roles`(ROLES_ID,ROLES_NAME,ROLES_UPDATE,ROLES_CREATE,ROLES_UPDATEBY,ROLES_CREATEBY) values (1,'admin','2015-08-13 14:19:05','0000-00-00 00:00:00',NULL,NULL);

/*Table structure for table `route` */

DROP TABLE IF EXISTS `route`;

CREATE TABLE `route` (
  `ROUTE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROUTE_DEST` varchar(100) DEFAULT NULL,
  `ROUTE_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ROUTE_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ROUTE_UPDATEBY` int(11) DEFAULT NULL,
  `ROUTE_CREATEBY` int(11) DEFAULT NULL,
  `ROUE_DEPARTURE` varchar(100) DEFAULT NULL,
  `ROUTE_ARRIVE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ROUTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `route` */

/*Table structure for table `status_transaction_rent` */

DROP TABLE IF EXISTS `status_transaction_rent`;

CREATE TABLE `status_transaction_rent` (
  `STATUS_TRANSACTION_RENT_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS_TRANSACTION_RENT_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `STATUS_TRANSACTION_RENT_CREATEBY` int(11) DEFAULT NULL,
  `STATUS_TRANSACTION_RENT_UPDATEBY` int(11) DEFAULT NULL,
  `STATUS_TRANSACTION_RENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS_TRANSACTION_RENT_NAME` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`STATUS_TRANSACTION_RENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `status_transaction_rent` */

/*Table structure for table `sub_modules` */

DROP TABLE IF EXISTS `sub_modules`;

CREATE TABLE `sub_modules` (
  `SUB_MODULES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUB_MODULES_NAME` varchar(100) DEFAULT NULL,
  `SUB_MODULES_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SUB_MODULES_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `SUB_MODULES_CREATEBY` int(11) DEFAULT NULL,
  `SUB_MODULES_UPDATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`SUB_MODULES_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Data for the table `sub_modules` */

insert  into `sub_modules`(SUB_MODULES_ID,SUB_MODULES_NAME,SUB_MODULES_CREATE,SUB_MODULES_UPDATE,SUB_MODULES_CREATEBY,SUB_MODULES_UPDATEBY) values (1,'view','2015-08-13 14:19:53','0000-00-00 00:00:00',NULL,NULL),(2,'edit','2015-08-13 14:19:55','0000-00-00 00:00:00',NULL,NULL),(3,'delete','2015-08-13 14:20:00','0000-00-00 00:00:00',NULL,NULL);

/*Table structure for table `ticket_transaction` */

DROP TABLE IF EXISTS `ticket_transaction`;

CREATE TABLE `ticket_transaction` (
  `TICKET_TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEMBER_ID` int(11) DEFAULT NULL,
  `STATUS_TRANSACTION_RENT_ID` int(11) DEFAULT NULL,
  `TICKET_TRANSACTION_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TICKET_TRANSACTION_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TICKET_TRANSACTION_CREATEBY` int(11) DEFAULT NULL,
  `TICKET_TRANSACTION_UPDATEBY` int(11) DEFAULT NULL,
  `TICKET_TRANSATION_CODE` varchar(50) DEFAULT NULL,
  `TICKET_TRANSACTION_PRICE` int(11) DEFAULT NULL,
  `TICKET_TRANSACTION_BUYERNAME` varchar(100) DEFAULT NULL,
  `TICKET_TRANSACTION_BUYERTELP` varchar(100) DEFAULT NULL,
  `TICKET_TRANSACTION_BUYEREMAIL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`TICKET_TRANSACTION_ID`),
  KEY `FK_RELATIONSHIP_1` (`STATUS_TRANSACTION_RENT_ID`),
  KEY `FK_RELATIONSHIP_10` (`MEMBER_ID`),
  CONSTRAINT `FK_RELATIONSHIP_1` FOREIGN KEY (`STATUS_TRANSACTION_RENT_ID`) REFERENCES `status_transaction_rent` (`STATUS_TRANSACTION_RENT_ID`),
  CONSTRAINT `FK_RELATIONSHIP_10` FOREIGN KEY (`MEMBER_ID`) REFERENCES `member` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `ticket_transaction` */

/*Table structure for table `ticket_transaction_detail` */

DROP TABLE IF EXISTS `ticket_transaction_detail`;

CREATE TABLE `ticket_transaction_detail` (
  `TICKET_TRANSACTION_ID` int(11) DEFAULT NULL,
  `TICKET_TRANSACTION_DETAIL_ARRIVETIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TICKET_TRANSACTION_DETAIL_DEPARTTIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TICKET_TRANSACTION_DETAIL_ARRIVE` varchar(100) DEFAULT NULL,
  `TICKET_TRANSACTION_DETAIL_DEPART` varchar(100) DEFAULT NULL,
  `TICKET_TRANSACTION_DETAIL_PRICE` int(11) DEFAULT NULL,
  `TICKET_TRANSACTION_DETAIL_CODE` varchar(100) DEFAULT NULL,
  KEY `FK_RELATIONSHIP_37` (`TICKET_TRANSACTION_ID`),
  CONSTRAINT `FK_RELATIONSHIP_37` FOREIGN KEY (`TICKET_TRANSACTION_ID`) REFERENCES `ticket_transaction` (`TICKET_TRANSACTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `ticket_transaction_detail` */

/*Table structure for table `transaction_type` */

DROP TABLE IF EXISTS `transaction_type`;

CREATE TABLE `transaction_type` (
  `TRANSACTION_TYPE_ID` int(11) NOT NULL,
  `TRANSACTION_TYPE_NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`TRANSACTION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `transaction_type` */

/*Table structure for table `travel_schedule` */

DROP TABLE IF EXISTS `travel_schedule`;

CREATE TABLE `travel_schedule` (
  `TRAVEL_SCHEDULE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROUTE_ID` int(11) DEFAULT NULL,
  `TRAVEL_SCHEDULE_PRICE` int(11) DEFAULT NULL,
  `TRAVEL_SCHEDULE_UPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TRAVEL_SCHEDULE_CREATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TRAVEL_SCHEDULE_UPDATEBY` int(11) DEFAULT NULL,
  `TRAVEL_SCHEDULE_CREATEBY` int(11) DEFAULT NULL,
  `TRAVEL_SCHEDULE_CAPACITY` int(11) DEFAULT NULL,
  `TRAVEL_SCHEDULE_ARRIVETIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TRAVEL_SCHEDULE_DEPARTTIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`TRAVEL_SCHEDULE_ID`),
  KEY `FK_RELATIONSHIP_8` (`ROUTE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_8` FOREIGN KEY (`ROUTE_ID`) REFERENCES `route` (`ROUTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `travel_schedule` */

/*Table structure for table `travel_transaction` */

DROP TABLE IF EXISTS `travel_transaction`;

CREATE TABLE `travel_transaction` (
  `TRAVEL_TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEMBER_ID` int(11) DEFAULT NULL,
  `TRAVEL_TRANSACTION_STATUS_ID` int(11) DEFAULT NULL,
  `TRAVEL_TRANSACTION_NAME` varchar(100) DEFAULT NULL,
  `TRAVEL_TRANSACTION_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TRAVEL_TRANSACTION_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TRAVEL_TRANSCATION_PRICE` int(11) DEFAULT NULL,
  `TRAVEL_TRANSACTION_CODE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`TRAVEL_TRANSACTION_ID`),
  KEY `FK_RELATIONSHIP_26` (`TRAVEL_TRANSACTION_STATUS_ID`),
  KEY `FK_RELATIONSHIP_33` (`MEMBER_ID`),
  CONSTRAINT `FK_RELATIONSHIP_26` FOREIGN KEY (`TRAVEL_TRANSACTION_STATUS_ID`) REFERENCES `travel_transaction_status` (`TRAVEL_TRANSACTION_STATUS_ID`),
  CONSTRAINT `FK_RELATIONSHIP_33` FOREIGN KEY (`MEMBER_ID`) REFERENCES `member` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `travel_transaction` */

/*Table structure for table `travel_transaction_status` */

DROP TABLE IF EXISTS `travel_transaction_status`;

CREATE TABLE `travel_transaction_status` (
  `TRAVEL_TRANSACTION_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRAVEL_TRANSACTION_STATUS_NAME` varchar(100) DEFAULT NULL,
  `TRAVEL_TRANSACTION_STATUS_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TRAVEL_TRANSACTION_STATUS_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TRAVEL_TRANSACTION_STATUS_UPDATEBY` int(11) DEFAULT NULL,
  `TRAVEL_TRANSACTION_STATUS_CREATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`TRAVEL_TRANSACTION_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `travel_transaction_status` */

/*Table structure for table `travel_transcation_detail` */

DROP TABLE IF EXISTS `travel_transcation_detail`;

CREATE TABLE `travel_transcation_detail` (
  `TRAVEL_TRANSACTION_ID` int(11) NOT NULL,
  `TRAVEL_SCHEDULE_ID` int(11) NOT NULL,
  PRIMARY KEY (`TRAVEL_TRANSACTION_ID`,`TRAVEL_SCHEDULE_ID`),
  KEY `FK_RELATIONSHIP_35` (`TRAVEL_SCHEDULE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_34` FOREIGN KEY (`TRAVEL_TRANSACTION_ID`) REFERENCES `travel_transaction` (`TRAVEL_TRANSACTION_ID`),
  CONSTRAINT `FK_RELATIONSHIP_35` FOREIGN KEY (`TRAVEL_SCHEDULE_ID`) REFERENCES `travel_schedule` (`TRAVEL_SCHEDULE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `travel_transcation_detail` */

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `USERS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERS_NAME` varchar(100) DEFAULT NULL,
  `USERS_USERNAME` varchar(100) DEFAULT NULL,
  `USERS_EMAIL` varchar(100) DEFAULT NULL,
  `USERS_PASSWORD` varchar(100) DEFAULT NULL,
  `USERS_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USERS_CREATEBY` int(11) DEFAULT NULL,
  `USERS_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `USERS_UPDATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`USERS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Data for the table `users` */

insert  into `users`(USERS_ID,USERS_NAME,USERS_USERNAME,USERS_EMAIL,USERS_PASSWORD,USERS_CREATE,USERS_CREATEBY,USERS_UPDATE,USERS_UPDATEBY) values (1,'admin','admin','admin@admin.com','21232f297a57a5a743894a0e4a801fc3','2015-08-17 13:49:40',NULL,'2015-08-17 06:45:19',1),(3,'RIPAS','bayu','ripas@rmail.com','123','2015-08-19 14:28:49',NULL,'0000-00-00 00:00:00',NULL);

/*Table structure for table `vehicle` */

DROP TABLE IF EXISTS `vehicle`;

CREATE TABLE `vehicle` (
  `VEHICLE_UPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VEHICLE_CAPACITY` int(11) DEFAULT NULL,
  `VEHICLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARTNER_ID` int(11) DEFAULT NULL,
  `VEHICLE_STATUS_ID` int(11) DEFAULT NULL,
  `CITY_ID` int(11) DEFAULT NULL,
  `VEHICLE_TYPE_ID` int(11) DEFAULT NULL,
  `VEHICLE_NAME` varchar(100) DEFAULT NULL,
  `VEHICLE_PHOTO` varchar(100) DEFAULT NULL,
  `VEHICLE_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VEHICLE_CREATEBY` int(11) DEFAULT NULL,
  `VEHICLE_UPDATEBY` int(11) DEFAULT NULL,
  `VEHICLE_DESCRIPTION` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`VEHICLE_ID`),
  KEY `FK_RELATIONSHIP_19` (`PARTNER_ID`),
  KEY `FK_RELATIONSHIP_21` (`VEHICLE_STATUS_ID`),
  KEY `FK_RELATIONSHIP_22` (`CITY_ID`),
  KEY `FK_RELATIONSHIP_7` (`VEHICLE_TYPE_ID`),
  CONSTRAINT `FK_RELATIONSHIP_19` FOREIGN KEY (`PARTNER_ID`) REFERENCES `partner` (`PARTNER_ID`),
  CONSTRAINT `FK_RELATIONSHIP_21` FOREIGN KEY (`VEHICLE_STATUS_ID`) REFERENCES `vehicle_status` (`VEHICLE_STATUS_ID`),
  CONSTRAINT `FK_RELATIONSHIP_22` FOREIGN KEY (`CITY_ID`) REFERENCES `city` (`CITY_ID`),
  CONSTRAINT `FK_RELATIONSHIP_7` FOREIGN KEY (`VEHICLE_TYPE_ID`) REFERENCES `vehicle_type` (`VEHICLE_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;

/*Data for the table `vehicle` */

insert  into `vehicle`(VEHICLE_UPDATE,VEHICLE_CAPACITY,VEHICLE_ID,PARTNER_ID,VEHICLE_STATUS_ID,CITY_ID,VEHICLE_TYPE_ID,VEHICLE_NAME,VEHICLE_PHOTO,VEHICLE_CREATE,VEHICLE_CREATEBY,VEHICLE_UPDATEBY,VEHICLE_DESCRIPTION) values ('2015-08-19 05:43:49',20,9,1,1,1,1,'avanza 234','7cbb62b87b12b18366e862b238e971d3.jpg','2015-08-19 12:27:09',NULL,NULL,'lala'),('2015-08-19 14:40:40',20,10,1,1,1,1,'avanza 234','ca17b14618dec33d55040a29810bee2b.jpg','2015-08-19 14:40:40',NULL,NULL,'lalal'),('2015-08-19 14:49:29',20,11,1,1,1,1,'avanza 234','97759dcebe5159125aafa9883c3dcda0.jpg','2015-08-19 14:49:29',NULL,NULL,'lalala');

/*Table structure for table `vehicle_status` */

DROP TABLE IF EXISTS `vehicle_status`;

CREATE TABLE `vehicle_status` (
  `VEHICLE_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `VEHICLE_STATUS_NAME` varchar(100) DEFAULT NULL,
  `VEHICLE_STATUS_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VEHICLE_STATUS_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `VEHICLE_STATUS_CREATEBY` int(11) DEFAULT NULL,
  `VEHICLE_STATUS_UPDATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`VEHICLE_STATUS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `vehicle_status` */

insert  into `vehicle_status`(VEHICLE_STATUS_ID,VEHICLE_STATUS_NAME,VEHICLE_STATUS_CREATE,VEHICLE_STATUS_UPDATE,VEHICLE_STATUS_CREATEBY,VEHICLE_STATUS_UPDATEBY) values (1,'bagus','2015-08-18 20:23:34','0000-00-00 00:00:00',NULL,NULL);

/*Table structure for table `vehicle_type` */

DROP TABLE IF EXISTS `vehicle_type`;

CREATE TABLE `vehicle_type` (
  `VEHICLE_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `VEHICLE_TYPE_NAME` varchar(200) DEFAULT NULL,
  `VEHICLE_TYPE_CREATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VEHICLE_TYPE_CREATEBY` int(11) DEFAULT NULL,
  `VEHICLE_TYPE_UPDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `VEHICLE_TYPE_UPDATEBY` int(11) DEFAULT NULL,
  PRIMARY KEY (`VEHICLE_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `vehicle_type` */

insert  into `vehicle_type`(VEHICLE_TYPE_ID,VEHICLE_TYPE_NAME,VEHICLE_TYPE_CREATE,VEHICLE_TYPE_CREATEBY,VEHICLE_TYPE_UPDATE,VEHICLE_TYPE_UPDATEBY) values (1,'mobil unyu','2015-08-18 20:23:47',NULL,'0000-00-00 00:00:00',NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
